# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.7.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: char

# 服务器配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8888
  # 应用相关配置
  servlet:
    # 应用的访问路径
    context-path: /kafka
  # tomcat相关配置
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
  # 切换不同的配置文件
  profiles:
      active: dev

# mybatis 配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.dpim.kafka.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    com.dpim: debug
    org.springframework: warn